### ISSUE TITLE
Good use case for a `switch` statement

### ISSUE THREAD

**Issue by 0xZakk** [nnguy152/01-Tower-of-Hanoi#12]
This is a great place to consider using a [`switch` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)

https://github.com/nnguy152/01-Tower-of-Hanoi/blob/10b7fbbb3c1888ee886377db33c8cdf53f53e422/script.js#L235-L266

**Comment by nnguy152** [comment]
Done! Thanks for the suggestion! 🔥
