### ISSUE TITLE
`onload` ͢ `startGame()` is 🔥

### ISSUE THREAD

**Issue by 0xZakk** [nnguy152/01-Tower-of-Hanoi#9]
This is really cool!

https://github.com/nnguy152/01-Tower-of-Hanoi/blob/10b7fbbb3c1888ee886377db33c8cdf53f53e422/script.js#L17-L22

One thing to think about: do you need the `addListeners()` method that you're calling inside the `startGame()` method?

**Comment by nnguy152** [comment]
I didn't. I got rid of it. Thanks 🙈

**Comment by 0xZakk** [comment]
🙌
